# Generated by Django 3.2.5 on 2024-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='Описание книги '),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена '),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название книги '),
        ),
    ]
