# Generated by Django 3.2.5 on 2024-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите название шоу')),
                ('description', models.TextField(verbose_name='Укажите описание шоу')),
                ('image', models.URLField(verbose_name='Вставьте ссылку на фото')),
                ('category', models.CharField(choices=[('Боевик', 'Боевик'), ('Детектив', 'Детектив'), ('Комедия', 'Комедия'), ('Фантастика', 'Фантастика'), ('Ужас', 'Ужас')], max_length=100, verbose_name='Выберите категорию фильма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
