# Generated by Django 3.2.5 on 2024-01-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvshow',
            options={'verbose_name': 'ТВ шоу', 'verbose_name_plural': 'ТВ шоу'},
        ),
    ]
