# Generated by Django 3.2.5 on 2024-01-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.TextField(choices=[('один', 'один'), ('два', 'два'), ('три', 'три'), ('четыре', 'четыре'), ('пять', 'пять')])),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_reviews', to='tv_show.tvshow')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
