# Generated by Django 3.2.5 on 2024-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persongame',
            options={'verbose_name': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='persongame',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='кажите описание'),
        ),
        migrations.AlterField(
            model_name='persongame',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Укажите имя игрока'),
        ),
    ]
