# Generated by Django 3.2.5 on 2024-01-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0002_auto_20240119_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persongame',
            options={'verbose_name': 'Персонажа', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
